services:
  spadeui:
    image: node:22
    container_name: spadeui
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "corepack enable && yarn install && yarn dev --port 3000 --host"
    environment:
      - NODE_ENV=development
