version: '3.8'
services:
  frontend:
    image: node:18
    container_name: spadeshaft
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn install && yarn dev --port 3000 --host"
    environment:
      - NODE_ENV=development
