server {
  listen       80;
  server_name  localhost;

  gzip on;
  gzip_vary on;
  gzip_types text/css text/javascript application/javascript application/json image/svg+xml;
  gzip_min_length 1024;

  location /media/ {
    alias /usr/share/nginx/media/;
  }
  location / {
    try_files $uri $uri/ /index.html;
  }
  client_max_body_size 100M;
}
